# Generated by Django 5.2.1 on 2025-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=50)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("forum", "Forum Diskusi"),
                            ("task", "Tugas"),
                            ("video", "Video Pembelajaran"),
                            ("quiz", "Kuis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Durasi dalam menit"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningProfile",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "avg_duration",
                    models.FloatField(verbose_name="Rata-rata Durasi Belajar (menit)"),
                ),
                (
                    "sessions_per_week",
                    models.FloatField(verbose_name="Sesi per Minggu"),
                ),
                (
                    "night_activity_freq",
                    models.FloatField(verbose_name="Frekuensi Aktivitas Malam"),
                ),
                (
                    "forum_vs_task",
                    models.FloatField(verbose_name="Rasio Forum vs Tugas"),
                ),
                (
                    "learning_type",
                    models.CharField(max_length=20, verbose_name="Tipe Belajar"),
                ),
                ("cluster", models.IntegerField(verbose_name="Cluster")),
            ],
        ),
        migrations.CreateModel(
            name="StudentActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="student_lea_student_cdb172_idx"
                    ),
                    models.Index(
                        fields=["start_time"], name="student_lea_start_t_031f99_idx"
                    ),
                ],
            },
        ),
    ]
